# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-19 00:58
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Encuentro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gol_equipo1', models.IntegerField(default=0)),
                ('gol_equipo2', models.IntegerField(default=0)),
                ('finalizado', models.BooleanField(default=False)),
                ('fecha_encuentro', models.DateTimeField()),
                ('fase', models.CharField(choices=[('GRUPOS', 'GRUPOS'), ('OCTAVOS DE FINAL', 'OCTAVOS DE FINAL'), ('CUARTOS DE FINAL', 'CUARTOS DE FINAL'), ('SEMIFINAL', 'SEMIFINAL'), ('TERCER PUESTO', 'TERCER PUESTO'), ('FINAL', 'FINAL')], default='GRUPOS', max_length=80)),
                ('tiempo_regular', models.BooleanField(default=True)),
                ('tiempo_extra', models.BooleanField(default=False)),
                ('gol_oro', models.BooleanField(default=False)),
                ('penales', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Encuentro',
                'verbose_name_plural': 'Encuentros',
            },
        ),
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre del Equipo', max_length=150)),
                ('continente', models.CharField(choices=[('AMERICA', 'AMERICA'), ('ASIA', 'ASIA'), ('AFRICA', 'AFRICA'), ('EUROPA', 'EUROPA'), ('OCEANIA', 'OCEANIA')], default='AMERICA', max_length=50)),
                ('bandera', models.FileField(blank=True, upload_to='banderas/')),
            ],
            options={
                'verbose_name': 'Equipo',
                'verbose_name_plural': 'Equipos',
            },
        ),
        migrations.CreateModel(
            name='Estadio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_estadio', models.CharField(max_length=250)),
                ('localidad', models.CharField(blank=True, max_length=250)),
            ],
            options={
                'verbose_name': 'Estadio',
                'verbose_name_plural': 'Estadios',
            },
        ),
        migrations.CreateModel(
            name='Grupo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
                ('descripcion', models.CharField(help_text='Descripcion del Grupo', max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='GrupoEquipos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('posicion', models.IntegerField(default=0)),
                ('equipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Tablero.Equipo')),
                ('grupo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Tablero.Grupo')),
            ],
        ),
        migrations.CreateModel(
            name='TablaGeneral',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puntos', models.IntegerField(default=0)),
                ('pj', models.IntegerField(default=0, help_text='Partidos Jugados', verbose_name='PJ')),
                ('pg', models.IntegerField(default=0, help_text='Partidos Ganados', verbose_name='PG')),
                ('pe', models.IntegerField(default=0, help_text='Partidos Empatados', verbose_name='PE')),
                ('pp', models.IntegerField(default=0, help_text='Partidos Perdidos', verbose_name='PP')),
                ('gf', models.IntegerField(default=0, help_text='Goles a Favor', verbose_name='GF')),
                ('gc', models.IntegerField(default=0, help_text='Goles en Contra', verbose_name='GC')),
                ('dif', models.IntegerField(default=0, help_text='Diferencia', verbose_name='DIF')),
                ('equipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Tablero.Equipo')),
            ],
            options={
                'verbose_name': 'Tabla General',
                'verbose_name_plural': 'Tabla General',
            },
        ),
        migrations.CreateModel(
            name='Quiniela',
            fields=[
                ('encuentro_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Tablero.Encuentro')),
                ('fecha', models.DateTimeField(auto_now=True)),
                ('jugador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            bases=('Tablero.encuentro',),
        ),
        migrations.AddField(
            model_name='encuentro',
            name='equipo1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Equipo1', to='Tablero.Equipo'),
        ),
        migrations.AddField(
            model_name='encuentro',
            name='equipo2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Equipo2', to='Tablero.Equipo'),
        ),
        migrations.AddField(
            model_name='encuentro',
            name='estadio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Tablero.Estadio'),
        ),
    ]
